server {
    listen 80;
    server_name _;

    gzip on;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/javascript application/javascript application/json image/svg+xml font/otf font/ttf;
    gzip_min_length 256;
    gzip_vary on;

    location / {
        return 301 /project-a/;
    }

    location /project-a/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /project-a/index.html;
    }

    location /project-a/api/ {
        rewrite ^/project-a/api/(.*) /api/v1/$1 break;
        proxy_pass http://fba_server:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
